baseURL = "https://example.com"
languageCode = "en-us"
title = "gob-theme"
theme="gob-theme"
copyright = ""
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false
	subtitle = "Minimal and Clean blog theme"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/stevegr33n"

#[[params.social]]
#name = "Twitter"
#icon = "twitter"
#url = "https://github.com/stevegr33n/"

#[[params.social]]
#name = "GitLab"
#icon = "gitlab"
#url = "https://github.com/stevegr33n/"
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
